#!/bin/bash

# Read config file
CONFIG="embar.config"
. $CONFIG

case "$1" in
    setup)
        # Get network interface
        INTERFACE=$(ifconfig | grep -E1 $EHA | grep -Eo 'en[0-9]*')

        # Set ip for gateway for beagbleboard
        # Need to do this as sudo
        echo "Set $INTERFACE to $GATEWAY_IP"
        ifconfig $INTERFACE $GATEWAY_IP
        ;;
    rconsole)

        # Script vars
        GZ="$APP_DIR.tar.gz"

        # Remove log files etc. before compress?

        # Go outside app dir, tar application dir, go back
        # This is so we don't get path contains .. on untaring
        echo "Tar $APP_DIR"
        cd ../
        tar zcf "$APP_DIR/$GZ" $APP_DIR
        cd $APP_DIR

        # Send compressed app over scp
        echo "Upload to $SSH_USER@$SSH_IP:$GZ"
        scp $GZ "$SSH_USER@$SSH_IP:$GZ"

        # Start ssh, untar file, cd to app dir, boot
        echo "Login to $SSH_USER@$SSH_IP"
        echo "Untar $GZ"
        echo "Boot $APP_DIR with $BOOT_CMD"
        SSH_CMD="tar zxf $GZ && cd $APP_DIR && $BOOT_CMD"
        ssh -t "$SSH_USER@$SSH_IP" $SSH_CMD
        ;;
    *)
        SCRIPT=$(basename $0)
        echo "Usage: $SCRIPT {rconsole|setup}"
        ;;
esac

exit 0